// /scripts/build.mjs
import { chmod, mkdir, rm } from "node:fs/promises";
import { build } from "esbuild";

await rm("dist", {
  recursive: true,
  force: true,
});

await mkdir("dist", {
  recursive: true,
});

await build({
  entryPoints: ["src/cli.ts"],
  outfile: "dist/cli.js",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  sourcemap: true,
  legalComments: "none",
  banner: {
    // yaml's CommonJS build requires Node built-ins from the standalone ESM bundle.
    js: `#!/usr/bin/env node
// Generated by scripts/build.mjs; do not edit.
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);`,
  },
});

await chmod("dist/cli.js", 0o755);
